language: python

sudo: false

python:
    - 2.7
    - 3.5
    - 3.6
    - pypy

install:
    - pip install --upgrade cython
    - pip install --upgrade .

script:
    - cd tests && python trial.py

notifications:
    email: false
